apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: flowforge-ml
  labels:
    app.kubernetes.io/name: vllm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
