singleNode: true
replicas: 1

resources:
  requests:
    cpu: "4"
    memory: 8Gi
  limits:
    cpu: "4"
    memory: 8Gi

config:
  opensearch.yml: |
    plugins.security.disabled: true

opensearchJavaOpts: "-Xmx4g -Xms4g"

persistence:
  enabled: true
  size: 100Gi
  storageClass: managed
  enableInitChown: false

service:
  type: ClusterIP
  port: 80  # AKS policy: only port 80 allowed (targetPort remains 9200 in chart)
