singleNode: true
replicas: 1

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 2Gi

config:
  opensearch.yml: |
    plugins.security.disabled: true

opensearchJavaOpts: "-Xmx1g -Xms1g"

persistence:
  enabled: true
  size: 100Gi
  storageClass: managed
  enableInitChown: false

service:
  type: ClusterIP
  port: 80  # AKS policy: only port 80 allowed (targetPort remains 9200 in chart)
