auth:
  enabled: true
  password: flowforge

architecture: standalone

# AKS policy: only port 80 allowed for services
master:
  service:
    ports:
      redis: 80
  persistence:
    enabled: true
    storageClass: managed
    size: 20Gi
  resources:
    requests:
      cpu: "500m"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

replica:
  replicaCount: 0

