apiVersion: v1
kind: Service
metadata:
  name: tei-reranker
  namespace: flowforge-ml
  labels:
    app.kubernetes.io/name: tei-reranker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tei-reranker
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
