apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flowforge-tei-reranker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: flowforge
  source:
    repoURL: https://github.com/tesco/flow-forge.git
    targetRevision: HEAD
    path: k8s/ml-serving/tei-reranker
  destination:
    server: https://kubernetes.default.svc
    namespace: flowforge-ml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
