auth:
  database: flowforge
  username: flowforge
  password: flowforge

global:
  storageClass: managed

primary:
  service:
    ports:
      postgresql: 80
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: managed
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  initdb: {}

metrics:
  enabled: false
