apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: flowforge-secrets
  namespace: flowforge
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: flowforge-kv
    - name: azureClientId
      value: ""  # Workload Identity

