apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: flowforge-ml
  labels:
    app.kubernetes.io/name: ollama
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http

