apiVersion: v1
kind: Service
metadata:
  name: tei-code
  namespace: flowforge-ml
  labels:
    app.kubernetes.io/name: tei-code
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tei-code
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
