apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tei-log-model-cache
  namespace: flowforge-ml
  labels:
    app.kubernetes.io/name: tei-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
