apiVersion: v1
kind: Service
metadata:
  name: tei-log
  namespace: flowforge-ml
  labels:
    app.kubernetes.io/name: tei-log
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tei-log
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
      name: http
